"""permit start_date nullable

Revision ID: 76b71b3d9a28
Revises: c096fc94de37
Create Date: 2025-11-11 07:48:46.801125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76b71b3d9a28'
down_revision: Union[str, Sequence[str], None] = 'c096fc94de37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('events', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('races', 'start_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('races', 'start_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
