"""add auth schema

Revision ID: c096fc94de37
Revises: e4d8a501a7b6
Create Date: 2025-10-31 16:19:44.068170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c096fc94de37'
down_revision: Union[str, Sequence[str], None] = 'e4d8a501a7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'organizations', ['user_id'])
    op.drop_constraint(op.f('organizations_admin_id_fkey'), 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['user_id'], ['id'])
    op.drop_column('organizations', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('organizations_admin_id_fkey'), 'organizations', 'users', ['admin_id'], ['id'])
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'user_id')
    # ### end Alembic commands ###
